spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
